import { describe, expect, it } from 'vitest'
import { hexToUint8Array, uint8ArrayToHex } from '../src/bytes/encoding.js'
import { Uint8ArrayReader } from '../src/chunk/byte-cursor.js'
import { Fork } from '../src/mantaray/fork.js'
import { MantarayNode } from '../src/mantaray/node.js'

const ENCODER = new TextEncoder()

function arbitraryReference(fill = 1): Uint8Array {
  return new Uint8Array(32).fill(fill)
}

describe('MantarayNode basic trie operations', () => {
  it('addFork splits shared prefixes into a compressed trie', () => {
    const node = new MantarayNode()
    node.addFork('foo', arbitraryReference())
    node.addFork('foobar', arbitraryReference())
    node.addFork('foobarbaz', arbitraryReference())
    node.addFork('fooxyz', arbitraryReference())

    expect(node.forks.size).toBe(1)
    expect(node.collect()).toHaveLength(4)

    expect(node.find('foo')).toHaveProperty('fullPathString', 'foo')
    expect(node.find('foobar')).toHaveProperty('fullPathString', 'foobar')
    expect(node.find('foobarbaz')).toHaveProperty('fullPathString', 'foobarbaz')
    expect(node.find('fooxyz')).toHaveProperty('fullPathString', 'fooxyz')

    const fooNode = node.find('foo')!
    expect(fooNode.path).toEqual(ENCODER.encode('foo'))
    expect(fooNode.forks.size).toBe(2)

    const foobarNode = node.find('foobar')!
    expect(foobarNode.path).toEqual(ENCODER.encode('bar'))
    expect(foobarNode.forks.size).toBe(1)

    const foobarbazNode = node.find('foobarbaz')!
    expect(foobarbazNode.path).toEqual(ENCODER.encode('baz'))
    expect(foobarbazNode.forks.size).toBe(0)
  })

  it('removeFork deletes a leaf and re-attaches its remaining descendants', () => {
    const node = new MantarayNode()
    node.addFork('foo', arbitraryReference())
    node.addFork('foobar', arbitraryReference())
    node.addFork('foobarbaz', arbitraryReference())
    node.addFork('fooxyz', arbitraryReference())

    node.removeFork('foobar')
    expect(node.find('foobar')).toBeNull()
    expect(node.find('foobarbaz')).toBeTruthy()
    expect(node.collect()).toHaveLength(3)

    node.removeFork('foobarbaz')
    expect(node.find('foobarbaz')).toBeNull()
    expect(node.collect()).toHaveLength(2)
  })

  it('handles long, deeply nested paths spanning multiple 30-byte segments', () => {
    const htmlPath = '/Code/Swarm/bee-js/test/coverage/lcov-report/index.html'
    const jsPath = '/Code/Swarm/bee-js/test/coverage/lcov-report/index.js'
    const dsStorePath = '/Code/Swarm/bee-js/test/coverage/.DS_Store'

    const node = new MantarayNode()
    node.addFork(htmlPath, arbitraryReference())
    node.addFork(jsPath, arbitraryReference())
    node.addFork(dsStorePath, arbitraryReference())

    expect(node.find(htmlPath)).toHaveProperty('fullPathString', htmlPath)
    expect(node.find(jsPath)).toHaveProperty('fullPathString', jsPath)
    expect(node.find(dsStorePath)).toHaveProperty('fullPathString', dsStorePath)
    expect(node.collect()).toHaveLength(3)

    node.removeFork(dsStorePath)
    expect(node.find(dsStorePath)).toBeNull()
    expect(node.find(htmlPath)).toHaveProperty('fullPathString', htmlPath)
    expect(node.collect()).toHaveLength(2)
  })

  it('collectAndMap returns a path -> hex reference map', () => {
    const node = new MantarayNode()
    const ref = arbitraryReference(7)
    node.addFork('a/b', ref)

    const map = node.collectAndMap()
    expect(map['a/b']).toBe(uint8ArrayToHex(ref))
  })
})

describe('MantarayNode marshal/unmarshal round-trip', () => {
  it('an untouched directory node keeps its forks after marshal -> unmarshalFromData', async () => {
    const node = new MantarayNode()
    node.addFork('/index.html', arbitraryReference(0xaa))
    node.addFork('/about.html', arbitraryReference(0xbb))

    const slash = node.forks.get('/'.charCodeAt(0))!.node
    expect(slash.path).toEqual(ENCODER.encode('/'))
    expect(slash.forks.size).toBe(2)

    const bytes = await slash.marshal()
    const restored = MantarayNode.unmarshalFromData(bytes, new Uint8Array(32))

    expect(restored.forks.size).toBe(2)
  })

  it('reads a real Bee-produced v0.2 directory node and re-marshals it byte-identically', async () => {
    // Generated by Bee's own mantaray MarshalBinary (bee/pkg/manifest/mantaray) for
    // a directory node ("/") with two value forks and a zero obfuscation key.
    // Sourced from bee-js's test/unit/manifest.spec.ts, itself an independently
    // observed real vector (not derived from this port).
    const vector =
      '00000000000000000000000000000000000000000000000000000000000000005768b3b6a7db56d21d1abff40d41cebfc83448fed8d7e9b06ec0d3b073f28f2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000202000000000000000000000000000000000000020a61626f75742e68746d6c0000000000000000000000000000000000000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa020a696e6465782e68746d6c0000000000000000000000000000000000000000bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
    const data = hexToUint8Array(vector)

    expect(data[63]).toBe(32) // Bee's reference-size byte for this directory node

    const node = MantarayNode.unmarshalFromData(data, new Uint8Array(32))

    expect(node.forks.size).toBe(2)
    expect(node.forks.get('a'.charCodeAt(0))!.prefix).toEqual(ENCODER.encode('about.html'))
    expect(node.forks.get('i'.charCodeAt(0))!.prefix).toEqual(ENCODER.encode('index.html'))

    // An untouched node must re-marshal to the exact same bytes Bee produced,
    // including each fork's preserved type byte (0x02 = value).
    expect(await node.marshal()).toEqual(data)
  })

  it('throws on invalid version hash', () => {
    const garbage = new Uint8Array(96).fill(1)
    expect(() => MantarayNode.unmarshalFromData(garbage, new Uint8Array(32))).toThrow(/version hash/)
  })

  it('throws on data shorter than the minimum header', () => {
    expect(() => MantarayNode.unmarshalFromData(new Uint8Array(10))).toThrow(/too short/)
  })
})

describe('MantarayNode.calculateSelfAddress / saveRecursively', () => {
  it('calculateSelfAddress is deterministic for identical trees', async () => {
    const a = new MantarayNode()
    a.addFork('foo', arbitraryReference())
    const b = new MantarayNode()
    b.addFork('foo', arbitraryReference())

    expect((await a.calculateSelfAddress()).toHex()).toBe((await b.calculateSelfAddress()).toHex())
  })

  it('calculateSelfAddress throws for an encrypted node (use saveRecursively instead)', async () => {
    const node = new MantarayNode({ encrypt: true })
    await expect(node.calculateSelfAddress()).rejects.toThrow(/encrypted/)
  })

  it('saveRecursively stores every node via onChunk and produces a self-consistent tree', async () => {
    const store = new Map<string, Uint8Array>()
    const onChunk = async (chunk: { hash(): { toHex(): string }; build(): Uint8Array }) => {
      store.set(chunk.hash().toHex(), chunk.build())
    }

    const root = new MantarayNode()
    root.addFork('index.html', arbitraryReference(1))
    root.addFork('about.html', arbitraryReference(2))
    root.addFork('images/logo.png', arbitraryReference(3))

    const { reference, rootChunk } = await root.saveRecursively(onChunk)

    expect(reference.length).toBe(32)
    expect(uint8ArrayToHex(reference)).toBe(rootChunk.hash().toHex())
    expect(store.has(uint8ArrayToHex(reference))).toBe(true)

    // Every fork's node got a real selfAddress assigned, and it matches a stored chunk.
    for (const fork of root.forks.values()) {
      expect(fork.node.selfAddress).not.toBeNull()
      expect(store.has(uint8ArrayToHex(fork.node.selfAddress!))).toBe(true)
    }
  })

  it('saveRecursively on an encrypted tree returns a 64-byte address||key reference', async () => {
    const store = new Map<string, Uint8Array>()
    const onChunk = async (chunk: { encryptedHash(key?: Uint8Array): { address: { toHex(): string } } }, key?: Uint8Array) => {
      if (key) {
        store.set(chunk.encryptedHash(key).address.toHex(), new Uint8Array(0))
      }
    }

    const root = new MantarayNode({ encrypt: true })
    root.addFork('index.html', arbitraryReference(1))

    const { reference, encryptionKey } = await root.saveRecursively(onChunk)

    expect(reference.length).toBe(64)
    expect(encryptionKey).toBeDefined()
    expect(encryptionKey!.length).toBe(32)
  })
})

describe('Fork.unmarshal', () => {
  it('rejects metadata claiming more bytes than remain in the reader', () => {
    // type byte with TYPE_WITH_METADATA (16) set, prefixLength 1, 30-byte prefix
    // slot, 32-byte address, then a metadata-length field claiming 1000 bytes
    // while none actually follow.
    const bogus = new Uint8Array(1 + 1 + 30 + 32 + 2)
    bogus[0] = 16
    bogus[1] = 1
    const metadataLengthOffset = 1 + 1 + 30 + 32
    bogus[metadataLengthOffset] = 0x03
    bogus[metadataLengthOffset + 1] = 0xe8 // 1000 in BE

    const reader = new Uint8ArrayReader(bogus)
    expect(() => Fork.unmarshal(reader, 32)).toThrow(/not enough bytes/)
  })
})
